### PR TITLE
Creating the mdb file for hyperfastcgi and moving it right beside the executable...

### PR DESCRIPTION
**Pull request by derFunk**
to enable debugging via remote debugger.

### CODE REVIEW

**Comment by xplicit** [comment]
Thanks for the pull request! mdb files with full debug info should definitely be generated in Debug profile. I'm not sure about Release profile, because adding `-debug` directive to compiler may hit performance. I did not research how `-debug` directive affects on performance on mono, but in .NET there is notice for performance in this mode:

https://msdn.microsoft.com/en-us/library/8cw0bt21.aspx

>If you use /debug:full, be aware that there is some impact on the speed and size of JIT optimized code and a small impact on code quality with /debug:full. We recommend /debug:pdbonly or no PDB for generating release code.    

So I would avoid to use `-debug` in release build before getting research results how this can affect performance on mono.

Also there is a build error when copying MDB files, which should be fixed.

**Comment by derFunk** [comment]
Hi Sergey,

I can confirm that mdb files are getting generated when building with the debug profile. But having the mdb files for the release build, which is optimized and does not have the other debug settings involved (like the debug preprocessor flag), makes sense for debugging like attaching the soft debugger.

I also did research on the performance hit of having built the release build with -debug, and there should be none. Only if the debugger is actually attached performance is influenced of course.

**Comment by xplicit** [comment]
Can you fix the build error so I would be able to merge it?

**Comment by derFunk** [comment]
I'm currently short of time so it can take a little until I can get back to this. But definitely on my list :)

**Comment by derFunk** [comment]
I changed the mdb generation in Release from `full` to `pdbonly` and fixed the installation.

**Pull request merged**
